### ISSUE TITLE
Nickname is not saving

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1432]
![image](https://cloud.githubusercontent.com/assets/1945230/13508710/cc11c418-e190-11e5-9c49-090c9ca76da1.png)
1. Enter some nickname
2. Push save
3. Leave page, for example to the dashboard
4. Go back
5. Nickname is empty

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Still not saving when creating...
When editing there is an error:
![image](https://cloud.githubusercontent.com/assets/1945230/13683782/546ff76e-e711-11e5-9474-2ec787d42729.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please look at this today
