### ISSUE TITLE
Unable to send test email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2944]
When I choose an email address from a saved email (i.e. you start to type, get the drop down below the field and select an email) the email address appears white in both email fields.

![image](https://cloud.githubusercontent.com/assets/2201340/23296127/c3be5e42-fac7-11e6-883e-bd0efde6d775.png)

When I test send to an existing profile I get the following error:

![image](https://cloud.githubusercontent.com/assets/2201340/23296030/6a8a2eb4-fac7-11e6-8574-6332edad5a95.png)

**Comment by bradmac** [comment]
Pretty sure that illegal repetition thing has been fixed. Might need to update libs to the latest.

**Comment by ducdhm** [comment]
Fixed! I also fixed on your admin console which you're working on ;)

**Comment by paddyow** [comment]
@ducdhm I can now send the email, but the email address is still appearing white for me.

**Comment by paddyow** [comment]
[ice_video_20170224-203018.zip](https://github.com/Kademi/kademi-dev/files/798828/ice_video_20170224-203018.zip)

**Comment by ducdhm** [comment]
Need to deploy

**Comment by hoanglinhlan** [comment]
passed
