### ISSUE TITLE
Editing data series record with incorrect profile causes common message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2983]
![image](https://cloud.githubusercontent.com/assets/1945230/23768170/c616c1ba-0513-11e7-9722-574f3af0fbe2.png)
Should be like on creation
![image](https://cloud.githubusercontent.com/assets/1945230/23768222/f8996912-0513-11e7-9678-4e49af1da259.png)

BTW, Couldnot locate profile or organisation: vladqas0031 - error in text

**Comment by bradmac** [comment]
@tannguyen3489 please integrate @ducdhm 's new jquery plugin for locating users and orgs

**Comment by tannguyen3489** [comment]
applied entityFinder plugin.

**Comment by hoanglinhlan** [comment]
current
I can save without saler or incorrect profile of sale by
https://lan-test.admin.kademi.com.au/sales/new-series1/72436211

**Comment by tannguyen3489** [comment]
@hoanglinhlan : I have just fixed it in the entityFinder lib. So, please wait to next deploying for checking.

**Comment by hoanglinhlan** [comment]
I still cant save with valid org
https://lan-test.admin.kademi.com.au/sales/new-series1/72436211
![image](https://cloud.githubusercontent.com/assets/20508726/26817165/ad974e4c-4abf-11e7-82f0-ea1137da1c4a.png)

**Comment by tannguyen3489** [comment]
@hoanglinhlan : it was fixed. Please wait for next deploy.

**Comment by tannguyen3489** [comment]
@hoanglinhlan : oh, I will deploy it for you. Sorry

**Comment by hoanglinhlan** [comment]
passed
