### ISSUE TITLE
[AU server] Handlebars versions conflict

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3586]
It was fixed on master, so please apply to AU server branch

https://github.com/Kademi/kademi-dev/commit/2f808c3e3305d4ab299bb36c299b26cbb69f5cd1

**Comment by ducdhm** [comment]
Fixed!

**Comment by bradmac** [comment]
Hey guys, i was still seeing this problem in CCA in .au, so i've hacked the dependencies.json for reporting-lib for now:
http://cca.admin.kademi.com.au/repositories/reporting-lib/1.1.1/admin/theme/apps/reporting-lib/texteditor?fileName=dependencies.json

Lets have a chat later.

**Comment by anhnt** [comment]
Worked ok on CCA now with stock reporting-lib
