### ISSUE TITLE
Carousel content editor problems

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3705]
This page has a carousel component at the top with 4 slides.
http://version1.brynnkelly.kademi.com.au/contenteditor?fileName=index.html

But the carousel content editor is not showing content for editing.
![image](https://user-images.githubusercontent.com/826458/28960903-6fe6cec4-7954-11e7-9bd6-04692a607617.png)

Also, there is another carousel further down the page with another 4 slides. These do show up in the editor, but when clicking the edit button the file upload button appears. However these slides have html content, so the content editor should display:
![image](https://user-images.githubusercontent.com/826458/28960979-b2e44ab2-7954-11e7-86a9-f07b0d430b53.png)

**Comment by salehh93** [comment]
done

**Comment by ducdhm** [comment]
@salehh93 What did you do? The issue here is carousel component doesnt detect HTML item of carousel. I have checked in brynnkelly and issue is still there. It's not fixed! Let @tannguyen3489 fixed it!

**Comment by ducdhm** [comment]
As discussed with @bradmac, we'll support editing caption for Image item. Editing caption with minimum toolbar of CKEditor.

**Comment by ducdhm** [comment]
New modal for editing caption of image item:
![newui](https://user-images.githubusercontent.com/1289631/29065932-e8545934-7c57-11e7-8cab-316e72e59a87.png)

**Comment by ducdhm** [comment]
Because default, bootstrap make caption align is center, I added a CSS rule for making default caption of carousel (Kademi's carousel with custom class is `carousel-fixed-height`) is left. This CSS rule doesnt impact to default bootstrap carousel.
