### ISSUE TITLE
Dynamic groups bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3904]
When you're dealing with numbers:
1. "Equal" doesn't work
2. "Not equals" doesn't work correctly (it returns all accounts)
3. "Less or equal" works like "Less" (it doesn't return value for "equal")
4. "Greater" works inproperly. It returns greater or equal values. (E.g. 29 > 29 return true which is wrong)

When you're dealing with text:
1. "Is empty" and "Is not empty" works inproperly, just returning all entries.
2. "Contains" works the same as "equal"
3. "Does not contain" doesn't work.

When you trying to check members of dyna-group, it showing membership count, but a list is empty
![image](https://user-images.githubusercontent.com/1945230/30583354-86bdc022-9d2f-11e7-8ead-cff6ceb7edd4.png)
![image](https://user-images.githubusercontent.com/1945230/30583374-8fb4d7c4-9d2f-11e7-8c06-6622dc3a1956.png)

**Comment by bradmac** [comment]
the group members page has been updated to work with dynamic groups. The appearance is slightly different from normal groups

![image](https://user-images.githubusercontent.com/826458/30729362-16ae476c-9fb3-11e7-8479-cd6a61ad1307.png)

**Comment by bradmac** [comment]
Issues with equals, contains, etc should all be fixed now

**Comment by Uafinder** [comment]
Numbers
"Less or equal" works like "Less" (it doesn't return value for "equal") - same
"Greater" works inproperly. It returns greater or equal values. (E.g. 29 > 29 return true which is wrong) - same

Text
"Equal" doesn't work
"Not equal" and "Not contain" works inproperly, just returning all entries.

http://vlad-test9.admin.kademi-ci.co/groups/DynaGroup2QA/
adminqa@mailinator.com

**Comment by bradmac** [comment]
> Numbers
"Less or equal" works like "Less"

Seems to work correctly to me.
- I have this user with birthdate 10/10/2007 - http://vlad-test9.admin.kademi-ci.co/manageUsers/136978/#general-tab
- I have a query setup for age=10
![image](https://user-images.githubusercontent.com/826458/31208652-0b61db5a-a9e3-11e7-9c22-fd4541af0dff.png)
http://vlad-test9.admin.kademi-ci.co/groups/brad-rule-test-01/

this query returns this user:
![image](https://user-images.githubusercontent.com/826458/31208669-1a4652cc-a9e3-11e7-9fda-15a794b33a6e.png)

- i change the query to be less then or equal, and this user is still shown:
![image](https://user-images.githubusercontent.com/826458/31208685-2f9863b8-a9e3-11e7-83cf-f97a51719d6a.png)

![image](https://user-images.githubusercontent.com/826458/31208695-3c2ba3ba-a9e3-11e7-94d7-4dbca58af2e3.png)

- if i change the age query to 11 the user is still shown. If i change to 9 it is not shown

So seems like "less or equal" is working correctly.

**Comment by bradmac** [comment]
> "Greater" works inproperly. It returns greater or equal values

I've found the opposite. A user which is returned for age = 10 is not returned (incorrectly) for age greater or equal 10, and also (correctly) not returned for greater then 10

**Comment by bradmac** [comment]
Fixed GTE with age field

**Comment by bradmac** [comment]
> Text "Equal" doesn't work

Problem appears to be that the query only works on lower case text. So we're now forcing the input text to lowercase, and that seems to fix this problem

**Comment by bradmac** [comment]
> "Not equal" and "Not contain" works inproperly, just returning all entries.

- "Not contain" wasnt implemented, is now.
- "Not equal" also needed lowercasing as above

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
http://vlad-test10.admin.kademi-ci.co/manageUsers
adminqa@mailinator.com
I've created a fresh account, with three users:
userqa01 - 01/01/1995 - eg 22
userqa02 - 01/01/1997 - eg 20
userqa03 - 01/01/1999 - eg 18

SO, let's start
1. Profile age equal
I've setup this condition, but it returns nothing
![image](https://user-images.githubusercontent.com/1945230/31214548-55e624ee-a9b4-11e7-8eea-e9fef05a75bb.png)
Som i've changed condition to 19 and it returns me 18-year old guy
http://vlad-test10.admin.kademi-ci.co/manageUsers/184491/#general-tab

The same with 20, when i setup 21 it successfully returns 20-years old guy

Is it possible that Birthday age parameter counts incorrect?

2. Profile email equal
It looks like a problem with "@" symbol while putting it in condition. I've place equal userqa01@mailinator.com and it doesn't return anything. I've change condition to "contains" and short value to "userqa01". It successfully process condition and return user. I've add @ to condition (e.g. "userqa01@") and it doesn't return anything. So probably problem with "@" symbol.

3. Birthday
It looks birthday parameter is not accessible at all.
I've created next condition.
http://vlad-test10.admin.kademi-ci.co/groups/DynaGroup3QA/
It should return all three users, but neither this condition nor simple equal doesn't work.
![image](https://user-images.githubusercontent.com/1945230/31217083-710b90b0-a9be-11e7-8d4e-7c2ad75610d1.png)

4. Contains DynamicGroup
Looks like condition where Dynamic Group addresses to Dynamic Group is not work.
http://vlad-test10.admin.kademi-ci.co/groups/DynaGroup4QA/

5. Dynamic group renaming
There is a trouble when rename dynamic group. 
I've create a group, then i want to rename it.
![image](https://user-images.githubusercontent.com/1945230/31217206-c9c64d58-a9be-11e7-9eea-035e1fdfb28e.png)
![image](https://user-images.githubusercontent.com/1945230/31217228-e0775f74-a9be-11e7-9ab5-d11068b00f39.png)
I'm forced to choose some radio-button, for example i choose Primary.
After this one all ok.
But the question, is it should be there at all?

**Comment by bradmac** [comment]
1. There was an off-by-one bug. That is fixed now, so someone born yesterday will be returned for age=0

**Comment by bradmac** [comment]
2 - yep, changed to use keyword field

**Comment by bradmac** [comment]
"3 - Birthday" - Needed to convert to a Long. Should be fixed now.

**Comment by bradmac** [comment]
"4 - Contains DynamicGroup" - This should be fixed now! Note, only supports contains and not-contains

**Comment by bradmac** [comment]
"5 - Dynamic group renaming" - should be fixed with this - https://github.com/Kademi/kademi-dev/issues/4099

**Comment by Uafinder** [comment]
1 - fixed
2 - fixed
3 - nope, still the same
4 - fixed
5 - understood

So, we have this at the moment:
3. Birthday
It looks birthday parameter is not accessible at all.
I've created next condition.
http://vlad-test12.admin.kademi-ci.co/groups/BirthdayDyna/
It should return this user
http://vlad-test12.admin.kademi-ci.co/manageUsers/515453/
But it returns nothing
![image](https://user-images.githubusercontent.com/1945230/31381841-62d4974a-adbe-11e7-9bec-ebfe0abc3353.png)


And some new:
6. Less 
Less condition works the same as Less and Equal
I've created next condition.
http://vlad-test12.admin.kademi-ci.co/groups/LessDyna/
it should return only one user:
http://vlad-test12.admin.kademi-ci.co/manageUsers/520086 which is 18 years old
However it returns another one, which is 20 years old
http://vlad-test12.admin.kademi-ci.co/manageUsers/502864
So this is incorrect

7. Condition with Birthday incorrect
I've created this condition
http://vlad-test12.admin.kademi-ci.co/groups/DynaGroup3QA/
when i try to access members page i have an error
![image](https://user-images.githubusercontent.com/1945230/31382116-472a2dec-adbf-11e7-8300-e52529a53753.png)
Probably should be some kind of validation.

**Comment by bradmac** [comment]
"3. Birthday - It looks birthday parameter is not accessible at all."

Just use greater/less then for birthday. I think its not realistic that a user will filter for a particular birthday. The reason its not matching is that the db records the exact date/time but we're just comparing to a date. I think this is fine.

**Comment by bradmac** [comment]
"6. Less" - Moved to separate issue

**Comment by bradmac** [comment]
"Condition with Birthday incorrect" - Thats an invalid query. We're not able to validate, so instead I've just added error handling so that condition will be ignored.

**Comment by bradmac** [comment]
"8. Phone field doesn't support characters "

Fixed:
![image](https://user-images.githubusercontent.com/826458/31416114-9210e7f0-ae83-11e7-88cb-793be5ea1b64.png)

![image](https://user-images.githubusercontent.com/826458/31416148-d23de26a-ae83-11e7-85f2-158d308938c6.png)

**Comment by bradmac** [comment]
"Profile orgs condition works only via OrgID"

Correct, this is intended behaviour

**Comment by Uafinder** [comment]
Ok, tested,
so closing it
