### ISSUE TITLE
Keditor poll and elearning panel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4022]
When dropping in either the poll or eLearning component:

1) Don't show the poll complete panel
2) Allow the admin to configure how many panels to show i.e. 1x poll or 4x learning modules - this will work like reward product lists when we can choose how many products to show i.e. 4 in rows of 2 for eaxmple

![image](https://user-images.githubusercontent.com/2201340/31052616-498e059a-a6d5-11e7-9c10-d922ec821206.png)

![image](https://user-images.githubusercontent.com/2201340/31052624-a1091526-a6d5-11e7-9e86-40fa36f35690.png)

**Comment by ducdhm** [comment]
As discussed with @bradmac:
 * Has limited number of tiles for each tile components
 * Size option with user-friendly names: Small, Medium, Large and Full-width

Note: no layout option because it's tile component and its layout is tile

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Number of modules does not work.  If I choose 2, it still shows all available modules.

User: http://paddy.admin.kademi-ci.co/manageUsers/101653/#summary-tab
Dashboard template http://paddy.admin.kademi-ci.co/pages/templates/version1/

![image](https://user-images.githubusercontent.com/2201340/31155887-339117a8-a8fd-11e7-9999-ab34828db4ca.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by paddyow** [comment]
When adding the component to a RHS column, I am getting unwanted padding left and right?

![image](https://user-images.githubusercontent.com/2201340/31260024-caa10f64-aa96-11e7-8423-7c4146ed5867.png)

**Comment by ducdhm** [comment]
@paddyow A thing you should remember about these kind of components. They're tile component. So you need to drop new container in RHS and then drop all tile components which you want into this container. KEditor will handle it by adding special class for container which contains only tile components
