### ISSUE TITLE
Points bucket showing when group is assigned 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4193]
This user http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

http://moblix.admin.kademi-ci.co/points-buckets - there are 2 buckets, both with a different group assigned. 

If a points bucket has a group selected, it should only show for that group.

![image](https://user-images.githubusercontent.com/2201340/31643874-be5523c0-b33e-11e7-8bd6-9deb23d7f231.png)

**Comment by anhnt** [comment]
done

**Comment by paddyow** [comment]
User http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

Still show extra points bucket in the profile panel.

**Comment by anhnt** [comment]
Fixed. Please update rewardstore-lib to check again
