### ISSUE TITLE
classes needs @Docs

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4253]
Here in following pages :
- @Docs needed . /hinda-settings/
- @Docs needed . /funnels/journey1/version1/#properties-tab

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/kademi-dev/issues/3478

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/client-hinda/issues/15

**Comment by gonzalon** [comment]
Profile page: 
![image](https://user-images.githubusercontent.com/2773216/32024937-c36e9d20-ba3a-11e7-98e8-2724e812094a.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , Here also we need @Docs , in "Stages" , "Customer Activities" : http://alaa-test16.admin.kademi-ci.co/funnels/journey1/version1/#properties-tab

![capture1](https://user-images.githubusercontent.com/26510030/32038150-48982ea8-ba31-11e7-8aeb-5d958ced044e.PNG)

**Comment by AlaaKhalaf94** [comment]
And here in accept modal :  http://alaa-test16.admin.kademi-ci.co/leads/1120117/#tasks-tab

![capture2](https://user-images.githubusercontent.com/26510030/32039254-0eabf8dc-ba36-11e7-95ce-c042216d405f.PNG)

**Comment by gonzalon** [comment]
Both should be fixed!

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , here in view lead page , in Tasks tab in "Task View Modal" : http://alaa-test19.admin.kademi-ci.co/leads/1234336/#tasks-tab
I still see the "$outcome.title"

![capture1](https://user-images.githubusercontent.com/26510030/32211424-193911b6-be1b-11e7-9614-852f590abf54.PNG)

**Comment by AlaaKhalaf94** [comment]
wait this issue to be closed to test : https://github.com/Kademi/kademi-dev/issues/4320

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon  , Here also we need @docs , in "Products log" in Hinda settings page : http://alaa-test28.admin.kademi-ci.co/hinda-settings/

![capture1](https://user-images.githubusercontent.com/26510030/32433565-125f2290-c2e4-11e7-9654-bd488f389de9.PNG)

**Comment by gonzalon** [comment]
Needs to be deployed

![image](https://user-images.githubusercontent.com/2773216/32526330-95447f8e-c48d-11e7-973f-45b6d1bf8c73.png)
