### ISSUE TITLE
Anonymous comments - online update

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4327]
Comments from other users don't appears when you on page - e.g. online comments appear (Facebook comments style).
http://vlad32-test.admin.kademi-ci.co/websites/vlad32-anontest
http://vlad32-anontest_vlad32-test.kademi-ci.co/

**Comment by tuzzmaniandevil** [comment]
Related to #4522

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33488399-21c3a97a-d6b9-11e7-879a-faf781b524e6.png)
![image](https://user-images.githubusercontent.com/1945230/33488419-2e6ec254-d6b9-11e7-9a50-d1746c1236cf.png)
Nope, comments doesn't appears
http://version1.vlad65-anon_vlad-test65.kademi-ci.co/anon.html

**Comment by bradmac** [comment]
Saw this, looks like a problem with the CI server:
```
An error occured: UncategorizedExecutionException[Failed execution]; nested: FileSystemException[/usr/share/elasticsearch/data/nodes/0/indices/mTH8PLYVSz-9TuaSmniGnA/0/index/_y.fdx: No space left on device]; - java.lang.RuntimeException: UncategorizedExecutionException[Failed execution]; nested: FileSystemException[/usr/share/elasticsearch/data/nodes/0/indices/mTH8PLYVSz-9TuaSmniGnA/0/index/_y.fdx: No space left on device];
```

**Comment by tuzzmaniandevil** [comment]
Fixed that issue :-) @Uafinder Can you please re-test?

**Comment by Uafinder** [comment]
Still doesn't work :(
![image](https://user-images.githubusercontent.com/1945230/33660277-fe357ed0-da8b-11e7-9cf9-236999e2f134.png)
![image](https://user-images.githubusercontent.com/1945230/33660284-037e81d4-da8c-11e7-85e5-9a9fd4c784f6.png)
After refresh
![image](https://user-images.githubusercontent.com/1945230/33660298-0e82034e-da8c-11e7-9b42-646ad438184a.png)
http://vlad-test69.admin.kademi-ci.co/websites/vlad69-anon/version1/#panel_apps-tab

**Comment by bradmac** [comment]
@Uafinder can you please confirm if this issue is still active in a new account? If so its high priority.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34939330-136d08e0-f9f4-11e7-8c7a-25cc7ed40c29.png)
![image](https://user-images.githubusercontent.com/1945230/34939351-1dc7b524-f9f4-11e7-882c-ddc19cd443cb.png)

I've create a site, and a page with comments only. Enable forums app and tracking app.
Then I go to separate browsers and leave a comment in one browser and it's not appear in second one...

https://vladtest22.admin.kademi-ci.co/
https://version1.vlad22comm-vladtest22.kademi-ci.co/page123.html
