### ISSUE TITLE
Dashboard alert content uploading something does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4458]
![image](https://user-images.githubusercontent.com/1945230/33017030-6a1599f4-cdf9-11e7-9905-760cfdad4f8e.png)
1. Go to dashboard alerts
2. Create one, upload some image for example
3. Upload does nothing.

**Comment by bradmac** [comment]
So the fundamental problem here is that dashboard alerts done operate within a repository, so there is no where to store images

I think we should wait for this - https://github.com/Kademi/kademi-dev/issues/4434

Then the user will be able to store images to, and select from, a media library which doesnt need a repo

**Comment by ducdhm** [comment]
@Uafinder Now, instead of Files tab, you should use Asset tab for upload image for Dashboard alert.

**Comment by Uafinder** [comment]
Hey,
I've install KAlerts app, create new alert, save it, and try to upload an image to Asset tab...
![image](https://user-images.githubusercontent.com/1945230/35102107-97a29ed6-fc6a-11e7-9e0d-e29e1719dc25.png)
Image doesn't appear and error in console appears.
http://vladtest23.admin.kademi-ci.co/manageAlerts/alert-4414234#bodyCopy-tab

**Comment by ducdhm** [comment]
@bradmac I have checked. After I upload to `/assets/_DAV/PUT?overwrite=true`. I'll get response like

```
[{"originalName":"10003465_10201051135041064_3723881164067704446_n.jpg","length":28549,"href":"/assets/4e6809ec-f17e-4437-be56-64a94982265b","contentType":"image/jpeg"}]
```

But when I access `/assets/4e6809ec-f17e-4437-be56-64a94982265b`, I got error page.

**Comment by ducdhm** [comment]
And it's working normally in locally.

**Comment by bradmac** [comment]
Didnt have transactions handling. Should be fixed now.

**Comment by bradmac** [comment]
hey @ducdhm, i can see this working fine locally, but having trouble getting it working on CI. Can you take a look please?

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Image looks good, but audio still failed
![image](https://user-images.githubusercontent.com/1945230/35143899-90dcd9ee-fd0b-11e7-82cd-293b08352a3b.png)
http://vladtest23c.admin.kademi-ci.co/manageAlerts/alert-4447274#bodyCopy-tab
1. Create alert
2. Try to upload audio

**Comment by bradmac** [comment]
@Uafinder audio is not currently supported. We will add that in the future but ignore it for now.

**Comment by bradmac** [comment]
> Also would be great to open Asset tab by default for uploading content for Alerts...

We just have the one UI for all screens, so we wont do that.

**Comment by Uafinder** [comment]
understood... so, closing
