### ISSUE TITLE
Journey title disappears after some actions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4526]
1. Create a journey
2. Open it, check that journey title is entered.
3. Go to builder, enter some blocks.
4. Leave page (go to another page, dashboard for example)
5. go to journey again
6. Check if title is entered - it's empty.
http://vlad-test64.admin.kademi-ci.co/funnels/journey5/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
Hey @ducdhm can you have a look at this please? But please just assign back to me if it needs back end changes, unless you want to have a crack at that yourself.

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Same thing here
Fresh account:
http://vlad-test66.admin.kademi-ci.co/funnels/journey-3/version1/#properties-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Nope, still the same..
Fresh account
http://vladtest03b.admin.kademi-ci.co/funnels/journey2/version1/#properties-tab

**Comment by Uafinder** [comment]
https://drive.google.com/open?id=1WywgKtFlp3Ajund_KfQb5jFmkH8ajGzv

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
yup, looks ok...
