### ISSUE TITLE
Member reporting component bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4573]
Please update this component to work with organisation based points.

When there are a lot of data which are should be visible, component edition become slow and caused errors. Some fields may not be deleted even you deselect a checkbox from the settings panel.
![image](https://user-images.githubusercontent.com/1945230/33609167-ba9ce94a-d9cf-11e7-97f4-5802792479ac.png)
![image](https://user-images.githubusercontent.com/1945230/33609181-c4cac900-d9cf-11e7-8f71-5c7ae8272342.png)
![image](https://user-images.githubusercontent.com/1945230/33609189-cb371e42-d9cf-11e7-905d-bb528cd528c9.png)
http://vlad-test68.admin.kademi-ci.co/pages/vlad68-repo/version1/?contenteditor=repo1.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Errors looks fine
But it's still doesn't work with organisation based points
![image](https://user-images.githubusercontent.com/1945230/37465347-91a9c2a0-2863-11e8-991d-53f90030ac38.png)
You could select only user oriented bucket.
http://vladtest41b.admin.kademi-ci.co/pages/vladtest41bpoints/version1/

**Comment by gonzalon** [comment]
Now if it is "ALL" its going to show the type of tx.
![image](https://user-images.githubusercontent.com/2773216/37572252-379b17f2-2b6d-11e8-8825-9797ca6b6144.png)

**Comment by Uafinder** [comment]
same for me, fresh account
http://vladtest44c.admin.kademi-ci.co/pages/vladtest44cweb/version1/
![image](https://user-images.githubusercontent.com/1945230/37662098-f9b675ce-2c5e-11e8-8681-75c2d446323c.png)
![image](https://user-images.githubusercontent.com/1945230/37662112-0175b3ba-2c5f-11e8-9e33-fcd77d35bdb3.png)
![image](https://user-images.githubusercontent.com/1945230/37662143-140f17fa-2c5f-11e8-97a2-ec242915b8a4.png)

**Comment by Uafinder** [comment]
hmmm... seeing it too...
well, let's close it for now... I will keep an eye on it
