### ISSUE TITLE
New photo plugin issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4663]
1. Uploading second image cause an error
https://github.com/Kademi/kademi-dev/issues/4630
![image](https://user-images.githubusercontent.com/1945230/34154209-5ed6afd0-e4bd-11e7-9505-ef157b5649be.png)

2. 
- Upload one image
- Click to edit
- Edit some
- click "back to upload"
- Click ok (without clicking on image name on the left)
- thumbnail would be bad
https://user-images.githubusercontent.com/1945230/34038768-21bfa2ca-e196-11e7-9fa1-ec9bfa08e9bc.png

3. 
- Upload one image
- Click to edit
- Edit some
- save image
- click "select" button again
- try to delete uploaded earlier image on the left
- would be an error
![image](https://user-images.githubusercontent.com/1945230/34154424-24971c3c-e4be-11e7-896e-8b9100556fc2.png)

4.
- click "select" button
- upload image (note that image is selected on the left panel)
- click ok
- thumbnail would be bad
![image](https://user-images.githubusercontent.com/1945230/34154506-62e75d4e-e4be-11e7-8ade-c15332dff5a8.png)

http://vladtest09.admin.kademi-ci.co/websites/vlad09lear/version1/programs/p1/c1/m2/#details-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4688

**Comment by Uafinder** [comment]
2,3,4 - fixed
1 - still appears
http://vladtest12.admin.kademi-ci.co/websites/vlad12-learn/version1/programs/p1/c1/m1/#details-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
yup, looks fine
