### ISSUE TITLE
KMediaLibrary: Integrate with image selection in page and edm editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4709]
Extends - https://github.com/Kademi/kademi-dev/issues/4434

Anywhere we can upload or select images and videos we should be able to upload to the media library and select from it. 

When browsing, it should only show assets of the appropriate type. Eg if inserting a video, only show assets which are videos

**Comment by bradmac** [comment]
First need an ajax/json search service available in the front end and admin

**Comment by bradmac** [comment]
Example search:
http://version1.assetw1-rootorg.loopbackdns.com:8080/assets/?q=doge

![image](https://user-images.githubusercontent.com/826458/34501076-2dc1d260-f072-11e7-8ec7-e0aa26c6475a.png)

**Comment by ducdhm** [comment]
@bradmac Can you add hash in response, too?

**Comment by bradmac** [comment]
@ducdhm note that assets dont live in the blob store, so you cant really use their hash for anything. This is intentional because we want assets to be self contained and associated with the client account only, but the blob store is always shared.

Note that the asset path is consistent in the admin and front end sites

So lets chat later

**Comment by bradmac** [comment]
Added support for PUT to asset resources to replace previous content

**Comment by ducdhm** [comment]
@bradmac 
1. Which request can I use for upload? Example: POST to `/assets/`
2. I send DELETE to `/assets/{uniqueID}` but it doesnt work
3. When send request to `/assets/?q=` to getting all assets, the format in response is empty

**Comment by bradmac** [comment]
> Which request can I use for upload? Example: POST to /assets/

I've added PUT support to /assets and /asset-manager

Note that you might want to use the JSON gateway rather then PUT directly to get more information

Eg instead of PUT /assets use POST /assets/_DAV/PUT using normal form multipart encoding

That will return a JSON response with name of the created resource.

**Comment by bradmac** [comment]
> I send DELETE to /assets/{uniqueID} but it doesnt work

Fixed

**Comment by bradmac** [comment]
> When send request to /assets/?q= to getting all assets, the format in response is empty

Fixed. But as discussed dont use this for filtering. Instead use the type parameter which does a prefix search on the format field

Eg curl -u admin:xxx -X GET http://localhost:8080/assets/?q=&type=video

```
{
   "data":[
      {
         "createdDate":1515029039110,
         "notes":"",
         "authorProfileId":2,
         "format":"image/jpeg",
         "modifiedDate":1515029039110,
         "name":"10450824_10203180208403339_3592593459663010136_n.jpg",
         "uniqueId":"76bb8995-fccf-447b-8620-6c83d58d6a43"
      },
      {
         "createdDate":1515029475908,
         "notes":"old photo",
         "authorProfileId":2,
         "format":"image/jpeg",
         "modifiedDate":1515029475909,
         "name":"10433863_10204135313845553_2100698384840684820_n.jpg",
         "uniqueId":"5940d784-fa81-4307-89cc-97724a8329d0"
      },
      {
         "createdDate":1515097984864,
         "notes":"",
         "authorProfileId":2,
         "format":"",
         "modifiedDate":1515097984864,
         "name":"asdasd",
         "uniqueId":"4573919a-cca5-4d1e-8619-f39e2589238b"
      },
      {
         "createdDate":1515446478748,
         "notes":"",
         "authorProfileId":2,
         "format":"video/mp4",
         "modifiedDate":1515446478748,
         "name":"kademi-pitch.mp4",
         "uniqueId":"1a181384-6e25-46b3-960c-5e33b673b7ea"
      },
      {
         "createdDate":1515446492283,
         "notes":"",
         "authorProfileId":2,
         "format":"video/mp4",
         "modifiedDate":1515446492283,
         "name":"channel-engagement-structure.mp4",
         "uniqueId":"2545b13f-9c3e-419f-a3ad-979e1689ecdd"
      },
      {
         "createdDate":1515039554985,
         "notes":"",
         "authorProfileId":2,
         "format":"",
         "modifiedDate":1515039554985,
         "name":"dddasd",
         "uniqueId":"b7e24266-6d7e-4d06-8096-1b1de82f7a74"
      }
   ],
   "fieldMessages":[

   ],
   "messages":[

   ],
   "nextHref":"",
   "status":true
}
```

**Comment by ducdhm** [comment]
@bradmac I do like this for uploading assets
```
use POST /assets/_DAV/PUT using normal form multipart encoding
```
But I got 404 error - NOT FOUND

**Comment by bradmac** [comment]
I'll look into that. But one thing i noticed is we're getting misalignment:

![image](https://user-images.githubusercontent.com/826458/34847844-8cc0cbd4-f781-11e7-8f0e-7e531ca1d4c4.png)

**Comment by bradmac** [comment]
I'm not seeing a 404 error, I'm seeing a NullPointerEx
```
INFO - io.milton.http.HttpManager  - POST :: version1.assetw1-rootorg.loopbackdns.com:8080///assets/_DAV/PUT start
INFO - io.milton.http.json.PutJsonResource  - processForm: class io.milton.cloud.server.apps.content.AssetsFolder
INFO - io.milton.http.json.PutJsonResource  - creating resource: jacinda.jpg size: 37966
ERROR- io.milton.http.StandardFilter  - exception sending content
java.lang.NullPointerException
	at co.kademi.server.content.AssetManager.uploadBinaryAsset(AssetManager.java:138)
	at io.milton.cloud.server.apps.content.AssetsFolder.createNew(AssetsFolder.java:81)
	at io.milton.http.json.PutJsonResource.processFile(PutJsonResource.java:186)
```

**Comment by bradmac** [comment]
Uploading works fine now, although the new image is not shown in the assets list:
![image](https://user-images.githubusercontent.com/826458/34848644-5a14a23e-f784-11e7-8d51-cd752ff7147b.png)

**Comment by bradmac** [comment]
@ducdhm here's a summary of changes we need:
- fix alignment of tabs header
- add asset to list after uploading, and select it in RHS
- we also need a search feature for assets, with text search and selecting by tag (eg asset types configured here http://localhost:8080/content/)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Hi @ducdhm we need the asset library to only display appropriate types of assets.

Eg if inserting an image, only show images
![image](https://user-images.githubusercontent.com/826458/35075714-96c761ba-fc59-11e7-9f97-d56060295499.png)

![image](https://user-images.githubusercontent.com/826458/35075744-ba49650c-fc59-11e7-8d50-8d10ab9309f7.png)

**Comment by bradmac** [comment]
Also, I've noticed that when selecting an image from the asset library and then clicking OK, it doesnt update the image in the content:
![image](https://user-images.githubusercontent.com/826458/35075864-60318bb6-fc5a-11e7-9455-e8eaef9077a8.png)

**Comment by bradmac** [comment]
So 2 issues
- ensure correct filtering when displaying asset library
- the image in the edited page is not updated when an image is selected from the asset library

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
> the image in the edited page is not updated when an image is selected from the asset library

I'm still seeing this problem locally (after autoloading updates)

![image](https://user-images.githubusercontent.com/826458/35131256-eb5e7594-fd29-11e7-8c93-a44b456bc956.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
@Uafinder ready to test.

Please ensure users can upload to the asset library from the editor, and can select images/videos from the editor.

This should just make it easier to manage lots of images and videos compared with the traditional folder based approach

**Comment by Uafinder** [comment]
1. Asset shows nothing by default
- I've create a page, add some image, push upload image, switch to assets and nothing appears there. However if I know the name it's possible to find image by name.
![image](https://user-images.githubusercontent.com/1945230/35443993-a7cad304-02b5-11e8-8c17-52361d6ed819.png)
![image](https://user-images.githubusercontent.com/1945230/35444008-b45488c2-02b5-11e8-9e88-fa2166968160.png)
http://vladtest28.admin.kademi-ci.co/pages/vlad28web/version1/

2. When you upload a file to asset via image selector it doesn't appear in left assets list

**Comment by ducdhm** [comment]
@bradmac Seems backend is changed. `http://localhost:8080/assets/?q=&type=` doesnt return any results anymore. Can you double-check it?

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
Opened some other issues... 
Most is ok at the moment
