### ISSUE TITLE
Signup component bugs - keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4840]
1. Display name fields checkbox will give visibility to Nickname field (Edit, display name, change it to yes, note that Nickname field appear)
![image](https://user-images.githubusercontent.com/1945230/35321556-bf7daebc-00ef-11e8-9c03-a367c2478562.png)

2. Display password field option appears twice
![image](https://user-images.githubusercontent.com/1945230/35321591-eca58338-00ef-11e8-8f06-ee8d2845bb3a.png)

3. Show orgs doesn't show anything
![image](https://user-images.githubusercontent.com/1945230/35321638-10df5814-00f0-11e8-8e31-a30de91d4025.png)

http://vladtest26.admin.kademi-ci.co/pages/vlad26website/version1/

**Comment by bradmac** [comment]
> Display name fields checkbox will give visibility to Nickname field

Correct, display name and nick name refer to the same thing.

**Comment by bradmac** [comment]
> Show orgs doesn't show anything

Note the orgs selector will only appear if there are orgs to select. Can you confirm you have setup orgs correctly?

**Comment by Uafinder** [comment]
> Note the orgs selector will only appear if there are orgs to select. Can you confirm you have setup orgs correctly?

yup, there are orgs present...

**Comment by Uafinder** [comment]
> Correct, display name and nick name refer to the same thing.
probably would be great to remove nickname option, or change it to yes when it's physically display

**Comment by bradmac** [comment]
> or change it to yes when it's physically display

sorry, what do you mean?

**Comment by Uafinder** [comment]
> sorry, what do you mean?

take a look on the screenshot again:
![image](https://user-images.githubusercontent.com/1945230/35321556-bf7daebc-00ef-11e8-9c03-a367c2478562.png)
1.Edit component 
2. display name change it to yes
3. note that Nickname field appear
4. note that Nickname option still says "no"

**Comment by anhnt** [comment]
Fixed, please update KSignup to 1.0.1

**Comment by Uafinder** [comment]
Looks good

**Comment by Uafinder** [comment]
2. Display password field option appears twice

This problem still appears...
http://vladtest30a.admin.kademi-ci.co/pages/vlad30aweb/version1/

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
