### ISSUE TITLE
Issues on image upload in email node - edm editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4856]
![image](https://user-images.githubusercontent.com/1945230/35439631-36774d7e-02a4-11e8-897d-2ceaea642310.png)
1. Create journey
2. Add send email node
3. add some content with image
4. upload some other image
http://vladtest28.admin.kademi-ci.co/funnels/first-journey/version1/email1/#message-tab
5. Note a bug on the left side
6. Then push button to edit image a bit
7. it will say that cropper error, and editor will look ugly.
![image](https://user-images.githubusercontent.com/1945230/35439738-b65644f0-02a4-11e8-9731-598a81a2100b.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4875

**Comment by Uafinder** [comment]
Error fixed...

But visual bug still appears:
![image](https://user-images.githubusercontent.com/1945230/35670690-dfe52d6c-0741-11e8-8522-558b8c6e879b.png)
http://vladtest28k.admin.kademi-ci.co/groupEmails/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Looks good!
