### ISSUE TITLE
EDM editor bug when changing image

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4898]
![image](https://user-images.githubusercontent.com/1945230/35858010-8b6365aa-0b43-11e8-94fa-3644878f5e5d.png)
http://vladtest30b.admin.kademi-ci.co/groupEmails/5087085/#messages-tab
1. Edit some email job
2. Add container (50/50) and image component to the body
3. Select or upload some big image (resolution 1600*1200 for example)
4. Click ok
5. It will use a image size of default image
6. Then upload or select some other image with smaller resolution (640*480 for example)
7. Click ok
8. It will take a size from a previous image and there will be mess on the screen.

**Comment by bradmac** [comment]
👍 

Yep, we seem to have lost this functionality when moving from the original photo component.

**Comment by ducdhm** [comment]
@Uafinder Can you double-check again? I have tested it and it's working normally.

**Comment by Uafinder** [comment]
https://drive.google.com/file/d/1S5R-j51VUocSqUPDQRDOz9xPq3PodQAE/view?usp=sharing

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Doh, nope it's not fixed.
You tried to raise Full width checkbox by default, but when you uploading next image it deselects this checkbox, and situation persists as well.
![image](https://user-images.githubusercontent.com/1945230/35913088-46749990-0c07-11e8-8418-b7d8375ce693.png)
http://vladtest30e.admin.kademi-ci.co/groupEmails/5170434/#messages-tab
Fresh account, libs updated, server restarted

**Comment by ducdhm** [comment]
@Uafinder I tested on the link which you provided me in incognitor tab but it's still working normal in my side. You can check my video at https://www.youtube.com/watch?v=pBOw0I2rLF4&feature=youtu.be 

Let's chat tomorrow if you still reproduce this issue.

**Comment by bradmac** [comment]
@Uafinder fyi I checked and i was able to upload multiple photos and seems to work ok

![image](https://user-images.githubusercontent.com/826458/35941997-1d4a814e-0cb9-11e8-8b52-355ddc110660.png)

**Comment by Uafinder** [comment]
Yeah, looks good for me too...
Will keep an eye on it
