### ISSUE TITLE
Create module page image component broken

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4902]
![image](https://user-images.githubusercontent.com/1945230/35862588-e2406998-0b54-11e8-92e7-9f7ea5651446.png)
1. Create a module
2. Press add page
3. Search for image component - it will not be in list
4. Then add some predefined template with image, but there no possibility to edit it.
http://vladtest30b.admin.kademi-ci.co/websites/vlad30bweb/version1/programs/p1/c1/m1/#files-tab

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Still the same
![image](https://user-images.githubusercontent.com/1945230/35912770-35a7bba2-0c06-11e8-805c-e30a27cc20d6.png)
http://vladtest30e.admin.kademi-ci.co/websites/vlad30eweb/version1/programs/p1/c1/m1/#files-tab
Fresh account, libs updated, server restarted

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Ok, now it gives an error when adding some image
![image](https://user-images.githubusercontent.com/1945230/35964752-6301f5e8-0cc1-11e8-9167-30f821fb96d2.png)

1. Push add a page
2. Wait while keditor loads
3. Add component with image
4. Watch for error
http://vladtest31a.admin.kademi-ci.co/websites/vlad31aweb/version1/programs/c1/c1/m1/#files-tab

**Comment by ducdhm** [comment]
@bradmac The problem is when creating new module page, the file name is blank. So the request to get components `/programs/p1/c1/m1/_components?fileName=` will return only module components. If I change fileName is "newFile", server will return all components include website and edm

**Comment by bradmac** [comment]
Eg full editor url:
http://version1.assetw1-rootorg.loopbackdns.com:8080/programs/p1/c1/normalmod/contenteditor?fileName=&url=http://localhost:8080/websites/assetw1/version1/programs/p1/c1/normalmod/

**Comment by bradmac** [comment]
Eg snippets url:
http://version1.assetw1-rootorg.loopbackdns.com:8080/programs/p1/c1/normalmod/_components?fileName=newFile

**Comment by bradmac** [comment]
The filename should be null in this case, not "newFile"

**Comment by bradmac** [comment]
in this case its checking the type of the folder.

previously folder resources did not express themselves as "html" resources, so it rejected most components

I've added "html" to the type list for folder resources

**Comment by bradmac** [comment]
@ducdhm can you please remove the "newFile" thing

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks better
