### ISSUE TITLE
Menu items not loading in Keditor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4917]
http://moblix.admin.kademi-ci.co/pages/moblixchannel/version1/

Open defaultThemeTemplate

![image](https://user-images.githubusercontent.com/2201340/35954718-5f797c5c-0cdf-11e8-9856-221c49b6a684.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Not fixed on US

http://moblix-coreloyalty.admin.kademi.us/pages/moblix-channel/version3/

Open defaultThemeTemplate

![image](https://user-images.githubusercontent.com/2201340/36762874-c1a89198-1c79-11e8-9e1e-98fa64e6ecce.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
Everything is good
