### ISSUE TITLE
De-dup orgs tool non-critical bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5003]
1. Should be sorting by title:
![image](https://user-images.githubusercontent.com/1945230/36370893-0b3cef9c-1569-11e8-91f9-47309125525c.png)

2. success pop-up should be tuned a bit
![image](https://user-images.githubusercontent.com/1945230/36371090-c727aada-1569-11e8-984e-bbcd6f3000e0.png)

3. when merging is done, organisation(s) which was just merged should be removed from the list
![image](https://user-images.githubusercontent.com/1945230/36371727-aec39b5a-156b-11e8-8ff0-8925592d3856.png)

4. Merge will fall to error when org will already contain both memberships
![image](https://user-images.githubusercontent.com/1945230/36372065-8cd3cd66-156c-11e8-9914-cc788fbd0d21.png)
![image](https://user-images.githubusercontent.com/1945230/36372073-955a8e20-156c-11e8-93a0-1472d05cd713.png)

**Comment by bradmac** [comment]
> It will not merge orgs when there are no users in it.

This is the only one that matters, the rest can be ignored

**Comment by bradmac** [comment]
> It will not merge orgs when there are no users in it.

I just checked with org0100 in your test account. Both orgs had no members, but they merged successfully, and the duplicate was removed.

**Comment by Uafinder** [comment]
weird thing...
I checked multiple times... let me reproduce it and I feedback

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/36374618-a32ea79a-1574-11e8-83d0-19b86b03e1cb.png)
![image](https://user-images.githubusercontent.com/1945230/36374630-aaacdb18-1574-11e8-856b-181a3d911ccf.png)
After refresh
![image](https://user-images.githubusercontent.com/1945230/36374644-b5a5ee74-1574-11e8-948b-23c7e9b0fb8c.png)

**Comment by bradmac** [comment]
> Should be sorting by title:
Done

> success pop-up should be tuned a bit
Improved

> when merging is done, organisation(s) which was just merged should be removed from the list
Now reloads after merge

> Merge will fall to error when org will already contain both memberships
The problem wasnt related to number of memberships, but is resolved.

**Comment by Uafinder** [comment]
error while merging orgs with both memberships still appears
![image](https://user-images.githubusercontent.com/1945230/36426337-67b65f6c-1652-11e8-8ad5-fae4faf398a6.png)
http://vladtest35a.admin.kademi-ci.co/organisations/dedupe
http://vladtest35a.admin.kademi-ci.co/manageUsers/6370057/#summary-tab

**Comment by bradmac** [comment]
Had an incorrect query term for the email field. Should be fixed now

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, looks so
