### ISSUE TITLE
keditor: no video preview when uploading video file

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5024]
![image](https://user-images.githubusercontent.com/1945230/36482438-fabd2b50-171b-11e8-81f0-60071aab466a.png)
1. Create a page
2. Edit
3. Add some video component
4. Change video
5. Upload some video
6. Video preview will not appear
http://vladtest36.admin.kademi-ci.co/pages/vladtest36web/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Still not appear
![image](https://user-images.githubusercontent.com/1945230/36545798-6cd016cc-17f2-11e8-8ad2-d443783d705e.png)
http://vladtest37.admin.kademi-ci.co/pages/vladtest37web/version1/
Fresh account

**Comment by ducdhm** [comment]
@Uafinder Seems like you forgot to sync content-lib? I have sync lib in root CI and create fresh account and everything works normally. Please double-check again.

**Comment by Uafinder** [comment]
Yup, looks fine
