### ISSUE TITLE
old style links cause frontend sites not open 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5110]
![image](https://user-images.githubusercontent.com/1945230/37333958-51e6a6f8-26b3-11e8-809e-7e4445271956.png)
From here
http://vladtest40e.admin.kademi-ci.co/websites/
![image](https://user-images.githubusercontent.com/1945230/37334012-709737ca-26b3-11e8-833c-5ff78c014f55.png)

**Comment by bradmac** [comment]
Updated the path resolved to always use the provided host format. I think will fix it.

**Comment by Uafinder** [comment]
ran build kademi task, cleared cache, but problem persists

**Comment by bradmac** [comment]
OK, should be fixed now. 

Now we're using the same format links for these buttons

**Comment by Uafinder** [comment]
same for me
did following again:
ran build kademi task, cleared cache, but problem is still there
![image](https://user-images.githubusercontent.com/1945230/37337650-a0a598f8-26bd-11e8-9dc5-5662572caab5.png)

**Comment by bradmac** [comment]
Looks ok now

**Comment by Uafinder** [comment]
yup, looks fine
