### ISSUE TITLE
EDM: password reset component doesn't display on the frontend email

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5142]
![image](https://user-images.githubusercontent.com/1945230/37524924-04766a60-2934-11e8-951b-7ed8eda42138.png)
http://vladtest42a.admin.kademi-ci.co/funnels/journey1/version1/email1/#message-tab
![image](https://user-images.githubusercontent.com/1945230/37524956-15598114-2934-11e8-9495-12067426c53c.png)

**Comment by anhnt** [comment]
tested with fresh account/website. the problem is Email app and email lib are not enabled for website by default so it cant render passwordResetLinkComponent

**Comment by bradmac** [comment]
The KJourneys app should have dependencies on the email app and email-lib

@anhnt can you add it please?

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Still doesn't work for me
Fresh account
http://vladtest44c.admin.kademi-ci.co/groupEmails/11367849/#messages-tab
![image](https://user-images.githubusercontent.com/1945230/37656531-f66a55ba-2c50-11e8-8c35-3fc337bbc7d2.png)
![image](https://user-images.githubusercontent.com/1945230/37656543-016a8d7c-2c51-11e8-8ddd-4a9675d619f7.png)

**Comment by bradmac** [comment]
@Uafinder this website doesnt have KJourneys installed - http://vladtest44c.admin.kademi-ci.co/websites/vladtest44cleads/version1/#panel_apps-tab

**Comment by bradmac** [comment]
I've added email dependencies to KTeam and KLeadMan

**Comment by Uafinder** [comment]
looks good for both journeys and leads
