### ISSUE TITLE
Content editor cant set container background image from asset

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5337]
ie it set the background image: http://deloitteweb-deloittefraudtraining.kademi.com.au/_hashes/files/339daa28-1696-44a3-a3de-86aabe90c8ee but the asset url should be different

**Comment by anhnt** [comment]
Fixed following components and stuff:
- Container background setting from asset
- Photo component from asset
- Carousel component from asset
- Thumbnail component from asset

@Uafinder please find more cases if they're using image from asset uploading modal so i can fix them all

**Comment by Uafinder** [comment]
Ok, background, photo and carousel work
Thumbnail component still failed
1. Add component
2. Select change photo
3. Upload new one
4. Press ok
5. It will not display on the frontend, and give an error in console
![image](https://user-images.githubusercontent.com/1945230/38986780-1b3f0a2e-43d6-11e8-8bee-2f712119eca7.png)
http://vladtest49e.admin.kademi-ci.co/pages/vladtest49eweb/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
Cant seem to be able to reproduce. Both CI and locally works ok
http://version1.vladtest49eweb-vladtest49e.kademi-ci.co/contenteditor?fileName=page1.html

**Comment by Uafinder** [comment]
Ok, thumbnail works
But the page background not work
![image](https://user-images.githubusercontent.com/1945230/39033926-08d01c14-447d-11e8-9f10-06ff58af8f65.png)
http://vladtest49h.admin.kademi-ci.co/pages/vladtest49hleads/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
yes this is new thing which needs to fix :)

**Comment by Uafinder** [comment]
Yeah, it works!
