### ISSUE TITLE
Asset manager keditor two photo components appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5398]
![image](https://user-images.githubusercontent.com/1945230/39524788-d268d7f6-4e22-11e8-9238-a4ce182d7faf.png)
http://vladtest50d.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by bradmac** [comment]
probably incorrect type detection

**Comment by anhnt** [comment]
@bradmac please see this http://vladtest51.admin.kademi-ci.co/asset-manager/_components?fileName=html

This returns both photo and photoEDM components. But in app.js we define types correctly

```
controllerMappings.addComponent("content/components", "photo")
        .addType("html")
        .desc("Photo block")

controllerMappings.addComponent("content/components", "photoEDM")
        .addType("edm")
        .desc("Photo block")

**Comment by bradmac** [comment]
Appears fixed now

**Comment by Uafinder** [comment]
Still appears
![image](https://user-images.githubusercontent.com/1945230/40426443-c3351cc2-5ea3-11e8-8714-668e4a5fd75a.png)
https://vladtest51w.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by anhnt** [comment]
Fixed please update libs to test

**Comment by Uafinder** [comment]
There are still two of them appears
![image](https://user-images.githubusercontent.com/1945230/42822876-d1851acc-89e4-11e8-9d4d-a77293e4f3ae.png)
http://vladtest53f.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by bradmac** [comment]
> There are still two of them appears

This problem applied to new (ie not saved) view only. I've updated to fix that by passing the type identifier to the request to get snippets and handlers

**Comment by bradmac** [comment]
See kademi.js

```
        var urlParams = new URLSearchParams(window.location.search);
        var format = urlParams.get("format");
        flog("format", format);
        if( format ) {
            pageName += "&format=" + format;
        }

```

**Comment by Uafinder** [comment]
Finally it's ok
