### ISSUE TITLE
Carters decimals issue in EDM

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5411]
![image](https://user-images.githubusercontent.com/1945230/39630587-6a95afc2-4fb8-11e8-8a67-8b1fd71359db.png)
https://carters.admin.kademi.com.au/groupEmails/116747588/edmeditor?fileName=index.html&useHash=true

FYI

**Comment by anhnt** [comment]
Fixed and patched to carters

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/39685694-8b1cf308-51ee-11e8-9239-9086f0b247f1.png)

**Comment by Uafinder** [comment]
You have applied this fix only for Keditor view... but preview and mostly vital in email body bug still appears
![image](https://user-images.githubusercontent.com/1945230/39688500-bf17df50-51db-11e8-9c65-4f6b8db60502.png)
![image](https://user-images.githubusercontent.com/1945230/39688508-c9d564bc-51db-11e8-8c61-76de4a12f4c4.png)
https://carters.admin.kademi.com.au/groupEmails/116747588/#messages-tab

**Comment by Uafinder** [comment]
Now looks fine
