### ISSUE TITLE
Problems duplicating automations with data series actions

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#543]
See https://github.com/Kademi/client-mercedes/issues/855#issuecomment-123255852

**Comment by bradmac** [comment]
"hi @bradmac
There are bugs in automation component duplicating. And I have an issue with saving automation component details.

Automation: Star Guild Cars - eLearning KPI
was copied into
Automation: Star Guild Vans - eLearning KPI

I found that not all actions came through

Moreover, I can't copy-pase and save details. When I save and reload the page, they disappear.

This is source details.
image

They appeared empty when I opened and checked copy.
And I can't save "Custom Field 2"
image

I have defined 3 extra fields in Manage Sales Data Star Guild Cars - eLearning
http://admin.mercedes.olhub.com/sales/star-guild-cars-elearning/"

**Comment by bradmac** [comment]
![a1](https://cloud.githubusercontent.com/assets/826458/8839430/66519c10-3129-11e5-82db-a4373d35d8df.png)
![a2](https://cloud.githubusercontent.com/assets/826458/8839431/6651f1e2-3129-11e5-9055-11fe5c75d43d.png)

**Comment by tuzzmaniandevil** [comment]
When duplicating an automation trigger it wasn't copying the custom fields across. This has been corrected.

**Comment by tuzzmaniandevil** [comment]
I can't reproduce the issue of Custom Field 2 not saving.

**Comment by DimitryNechaev** [comment]
hi @tuzzmaniandevil 

why I still can't save Custom Field 2 as on the picture above?

https://github.com/Kademi/client-mercedes/issues/855

**Comment by DimitryNechaev** [comment]
here is automation link http://admin.mercedes.olhub.com/autoEmails/star-guild-cars-elearning-kpi(1)/#action-tab
