### ISSUE TITLE
Voucher pdf preview doesnt render image from assets because of ssl

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5477]
The LH image is printed because i edit source to be https
The RH image is not printed because its from asset and the url is generated from java which starts without https

![image](https://user-images.githubusercontent.com/735555/40532439-a5fed986-6029-11e8-8725-855354f6a800.png)

https://airnz.admin.kademi.com.au/voucher-type/test4/V-9d2

![image](https://user-images.githubusercontent.com/735555/40532457-b389c0b6-6029-11e8-8c45-3e0f236fe654.png)

![image](https://user-images.githubusercontent.com/735555/40532476-c2655442-6029-11e8-8f31-b8d40f9a7a7b.png)

**Comment by bradmac** [comment]
I've updated the function that generates the URL for photo components to use SSL if its forced on the website. So that should solve this problem.

**Comment by Uafinder** [comment]
Prod still the same... or this is on QA?
https://airnz.admin.kademi.com.au/voucher-type/test5/VOUCH-9e463

**Comment by bradmac** [comment]
hey @Uafinder please check the deployments chat group to see when we do prod deploys
https://chat.kademi.co/channel/deployment-followup

No delpoy to prod yet..

**Comment by Uafinder** [comment]
looks good now
