### ISSUE TITLE
Admin products page: cant go to page 2

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5775]
Please see here http://viri.admin.kademi.com.au/reward-store/viridianclub-store/?q=&categoryName=&sortfield=p.name&sortdir=asc

I saw js and see that it doesnt get pagination params to build new url via pushState

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
still doesn't work, but without JS error
http://vladtest53x.admin.kademi-ci.co/reward-store/vladtest53xrew-store/?addProducts&q=&l=
try here
Click on second page, it will display you a second page for some seconds and then move it to first page again...

**Comment by anhnt** [comment]
Fixed, this is different screen though

**Comment by Uafinder** [comment]
Still doesn't work for me
http://vladtest53z.admin.kademi-ci.co/reward-store/vladtest53zaucstore-store/?addProducts=&q=&l=&startPos=0
Click on second page, it will display you a second page for some seconds and then move it to first page again...

**Comment by anhnt** [comment]
Finally fixed, tested on your page above

**Comment by Uafinder** [comment]
looks good
