### ISSUE TITLE
Ability to duplicate articles under Content -> Blogs

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#5778]
I am using Blogs as Case studies and it has a complex layout which would be a hassle for the client to create from scratch each time they want to add a new case study so It would be great to have the ability to duplicate the articles in Blogs so they have a template to start with. (just like we do in other sections of Kademi i.e .html pages etc).

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43612796-7b906192-9701-11e8-8823-d81fe1b7d174.png)

**Comment by yrsengar** [comment]
The duplication feature working really well except I am facing one issue with the content tab.
When I duplicate an article, it is an exact copy of the original which is great but when I try to edit the copied article first of all the "Edit content" button is disabled so I can't edit content.
I noticed that the "Edit content" button activates when I use it once I used the "Save changes" button.
When I click on "Edit content" button I see a blank page, the content that was copied from the original article isn't available anymore.
Screenshots attached below:
![image](https://user-images.githubusercontent.com/10014469/43814176-159ce9d0-9b1d-11e8-973b-7d8bfa5dbe94.png)

**Comment by Uafinder** [comment]
1. Duplicate article
2. New article is published instantly (which is incorrect)
3. You reject article and try to edit content
4. Edit button is not active

![image](https://user-images.githubusercontent.com/1945230/43830626-675fd6d2-9b0a-11e8-9074-c7e4c4000a8b.png)
http://vladtest53ooo.admin.kademi-ci.co/blogs/blog/article12/#bodyCopy-tab

**Comment by bradmac** [comment]
Should be fixed. Also added date column to  blog article list

**Comment by Uafinder** [comment]
Group visiblity doesn't copy as well as files
Original
http://vladtest54.admin.kademi-ci.co/blogs/myblog1/new1/#groups-tab
Copy
http://vladtest54.admin.kademi-ci.co/blogs/myblog1/new13/#files-tab

**Comment by Uafinder** [comment]
Files now copying,
but still not copying:
- group access
- tags
- category

orig
http://vladtest54a.admin.kademi-ci.co/blogs/blog/article-orig
copy
http://vladtest54a.admin.kademi-ci.co/blogs/blog/article-orig2

**Comment by bradmac** [comment]
> tags, category

These cant copy because they're defined by each blog.

**Comment by bradmac** [comment]
> but still not copying    group access

There was an error and groups were being overwritten with blank. Fixed

**Comment by Uafinder** [comment]
Finally looks good
