### ISSUE TITLE
KCRM: Contact list page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5849]
![image](https://user-images.githubusercontent.com/826458/44314704-debc2f00-a46f-11e8-9b9d-67c8c0a0ef11.png)
https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86132662/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
Please update button layout to match creative.

Remove the add contact button, since thats now in the menu

![image](https://user-images.githubusercontent.com/826458/44314726-09a68300-a470-11e8-922e-3166fb48074f.png)

**Comment by Uafinder** [comment]
Ok, looks good, but there is an issue when doing some operations
For example
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/custs/
then use search
then clear search results
![image](https://user-images.githubusercontent.com/1945230/44390614-666c7100-a536-11e8-9594-77809295f201.png)
then try to add new contact or delete, or even sort
it will complete operation, but will not update list
![image](https://user-images.githubusercontent.com/1945230/44390664-7edc8b80-a536-11e8-8c87-e24b0084cd0c.png)
![image](https://user-images.githubusercontent.com/1945230/44390674-86039980-a536-11e8-89c7-b37f7eeecaf7.png)

Unchecking all customers checkbox doesn't cause to remove checkboxes from customers
![image](https://user-images.githubusercontent.com/1945230/44390761-be0adc80-a536-11e8-8f7b-65dfb194741a.png)

http://vladtest53ssweb-vladtest53ss.kademi-ci.co/custs/

upload CSV doesn't filter files by type, it show images, videos and so on
![image](https://user-images.githubusercontent.com/1945230/44390836-f01c3e80-a536-11e8-9c64-82f435ef2cfe.png)

when import completed and data is indexing, progress bar throws to 0
![image](https://user-images.githubusercontent.com/1945230/44391012-60c35b00-a537-11e8-9ba7-301590c3c87d.png)

error in console after import is completed
![image](https://user-images.githubusercontent.com/1945230/44391029-6d47b380-a537-11e8-9a73-0e3f7583d229.png)

error in console - appears when paginator appears
![image](https://user-images.githubusercontent.com/1945230/44391099-a6802380-a537-11e8-85af-0088ad32808d.png)

paginator visual look should be improved, add padding and from top and from left

**Comment by anhnt** [comment]
Fixed
Note that we hide Upload button for now so issues relates to that will be ignored

**Comment by Uafinder** [comment]
1. First issue persists partially
use search
then clear search results
then try to use sorting and it will not work

2. Last contact date should have more left alignment, bigger fontsize and normal date tip
![image](https://user-images.githubusercontent.com/1945230/44659966-b94e9880-aa0e-11e8-9725-76cad7660243.png)

3. paginator should have page size selector

4. When you search something when you're not on the first page, your result always be null
![image](https://user-images.githubusercontent.com/1945230/44660032-fc107080-aa0e-11e8-9c21-b8f4dd227269.png)
![image](https://user-images.githubusercontent.com/1945230/44660039-029ee800-aa0f-11e8-8b81-bcb3dc1c5698.png)

**Comment by anhnt** [comment]
All sorted

**Comment by Uafinder** [comment]
looks good
