### ISSUE TITLE
KCom2 - checkout, shipping address does not prepopulate state address from dropdown.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6054]
initial poking about shows that profile state says **name="addressState"** and shipping address says **name="state"**.

I can see via console that the data parses correctly:
<img width="334" alt="parses-correct-data" src="https://user-images.githubusercontent.com/39784677/46325238-d6046e80-c653-11e8-98e0-0fbc26c407bc.png">

However I think because of the naming mismatch, the data is not applied correctly.

All fields empty:
<img width="375" alt="default-state" src="https://user-images.githubusercontent.com/39784677/46325245-e4eb2100-c653-11e8-9776-555a5841052b.png">

And state is still empty.
<img width="376" alt="updated-state" src="https://user-images.githubusercontent.com/39784677/46325250-ea486b80-c653-11e8-807f-98f47688656d.png">

... over to you @anhnt

**Comment by stephen-fueldesign** [comment]
Here's my testing:
https://plantae.co.nz/online-store/cart

**Comment by anhnt** [comment]
Fixed in version 1.1.6

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/6134
https://github.com/Kademi/kademi-dev/issues/6136

**Comment by bradmac** [comment]
OK, so looks like this issue can be closed. Other issues still to be processed
