### ISSUE TITLE
Kcom2: Create pointsBalanceEDMComponent, pointsEarnedEDMComponent and pointsExpiringEDMComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6613]
Create pointsBalanceEDMComponent, pointsEarnedEDMComponent and pointsExpiringEDMComponent
in Kcom2

**Comment by trungjc** [comment]
Update in version 1.7.7

**Comment by trungjc** [comment]
Fix color picker bug on version 1.7.8

https://github.com/Kademi/kademi-dev/commit/fb16778e928e359380fe03520dd9945e37aee869

**Comment by trungjc** [comment]
Move the components to reward-lib

pointsBalanceEDMComponent => rewardPointsBalanceEDMComponent 
pointsEarnedEDMComponent => rewardPointsEarnedEDMComponent 
pointsExpiringEDMComponent => rewardPointsExpiringEDMComponent 

Required reward-lib version 1.2.5 and Kcom2 version 1.7.9

**Comment by Uafinder** [comment]
There are doubles for every points component
![image](https://user-images.githubusercontent.com/1945230/51682592-70683380-1ff0-11e9-90e6-3c9ca7e662f6.png)
http://vladtest56dd.admin.kademi-ci.co/groupEmails/18662504/edmeditor?fileName=index.html&useHash=true

**Comment by trungjc** [comment]
It is duplicated because we are using same resource (component thumbnail) in the components for both rewardstore-lib and reward-lib. We should not change them.

![screenshot_6](https://user-images.githubusercontent.com/704946/51724523-541bd380-2090-11e9-893b-715fdbf1fced.png)
![screenshot_7](https://user-images.githubusercontent.com/704946/51724525-541bd380-2090-11e9-9465-86f79bb9ec97.png)

**Comment by bradmac** [comment]
@Uafinder the use of rewardstore-lib is deprecated. This is needed for legacy clients using RewardStoreApp.

But new clients should use KCommerce2.

It is not valid to use rewardstore-lib and KCommerce2 at the same time, use one or the other.

**Comment by Uafinder** [comment]
Expiry component doesn't show correctly
![image](https://user-images.githubusercontent.com/1945230/52423402-b64ced80-2b00-11e9-99b2-e781d43aa04a.png)
http://vladtest56mm.admin.kademi-ci.co/emails/18755765
![image](https://user-images.githubusercontent.com/1945230/52423438-cc5aae00-2b00-11e9-9cef-84287ab090a1.png)
http://vladtest56mm.admin.kademi-ci.co/manageUsers/18755691/#pointsBucketTab-tab

**Comment by Uafinder** [comment]
Also i still seeing doubling for all three components
![image](https://user-images.githubusercontent.com/1945230/52423641-2e1b1800-2b01-11e9-903e-e2a756e18783.png)
http://vladtest56mm.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-405cd5/#message-tab

But rewardstore-lib disabled
![image](https://user-images.githubusercontent.com/1945230/52423742-67538800-2b01-11e9-8e44-673e3f69126b.png)

**Comment by bradmac** [comment]
still enabled at the account level:

![image](https://user-images.githubusercontent.com/826458/52436107-424e2c00-2b78-11e9-9063-d4144d63af8b.png)

**Comment by bradmac** [comment]
@anhnt please check the points manager api is being used correctly

Also, these components currently have the Carters brand colours set as default. We really cant do that, so please change to some generic layout and colours.

**Comment by anhnt** [comment]
Fixed rewardPointsExpiringEDMComponent and default colors

rewards-lib 1.2.6

**Comment by Uafinder** [comment]
Expiring points still doesn't work
![image](https://user-images.githubusercontent.com/1945230/52848222-dab75400-3116-11e9-9014-3300c59a909f.png)
http://vladtest56r.admin.kademi-ci.co/emails/18775910
I think that's due to group empty parameter, but i think it should not be mandatory to select

**Comment by Uafinder** [comment]
ok, looks good
