### ISSUE TITLE
Improve admin leads page and add to menu

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6617]

**Comment by bradmac** [comment]
requires leadman-lib 3.3.9 and platform update

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/51644745-296d4480-1fd6-11e9-810b-4a87aa61e23c.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/51683846-74498500-1ff3-11e9-9c28-cbcc14d117d2.png)
- This links leads to error, because they are journey related
http://vladtest56ddd.admin.kademi-ci.co/leads/

- Search not case sensitive, e.g. userqa01 is ok, userqa is not.
![image](https://user-images.githubusercontent.com/1945230/51684009-c7bbd300-1ff3-11e9-90f5-7bcc6dc8362a.png)

- Not seeing any menu item for Leads page
![image](https://user-images.githubusercontent.com/1945230/51684080-f20d9080-1ff3-11e9-9533-e2951f25fde7.png)

- Should be Journey column i think, to see which journey lead from (or filter)

**Comment by bradmac** [comment]
> This links leads to error, because they are journey related

Fixed

**Comment by bradmac** [comment]
> Search not case sensitive, e.g. userqa01 is ok, userqa is not

OK for now

**Comment by bradmac** [comment]
> Not seeing any menu item for Leads page

Fixed

> Should be Journey column i think, to see which journey lead from (or filter)

Added

> add pagination as well

That would be nice, but not a priority at the moment

**Comment by Uafinder** [comment]
Search still not working for me on fresh account
![image](https://user-images.githubusercontent.com/1945230/52845276-5ca37f00-310f-11e9-8b2f-fbeafa6d646d.png)
http://vladtest56r.admin.kademi-ci.co/leads/?leadsSearch=userqa0

**Comment by bradmac** [comment]
The page does a terms query, not prefix. Works correctly:

![image](https://user-images.githubusercontent.com/826458/52919302-c917bb80-3365-11e9-869c-7ad8b93b2b6a.png)

**Comment by Uafinder** [comment]
Ok, looks good
