### ISSUE TITLE
Add link to SMS details page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6689]
Here
![image](https://user-images.githubusercontent.com/1945230/52473645-fc588e80-2b9e-11e9-8397-d075d0ffce8f.png)
http://vladtest56mmm.admin.kademi-ci.co/manageUsers/18757623/#summary-tab

Here
![image](https://user-images.githubusercontent.com/1945230/52473689-1db97a80-2b9f-11e9-90aa-837e16c3ae54.png)
http://vladtest56mmm.admin.kademi-ci.co/smsHistory/

Should lead here
http://vladtest56mmm.admin.kademi-ci.co/smsHistory/18757636

**Comment by bradmac** [comment]
Fixed. Requires platform update.

**Comment by Uafinder** [comment]
ok, you added it to profile page, but it's still doesn't work on SMS history page
![image](https://user-images.githubusercontent.com/1945230/52560571-6c664f00-2e01-11e9-82d2-486b5facffd1.png)
http://vladtest56n.admin.kademi-ci.co/smsHistory/

**Comment by bradmac** [comment]
Done. Requires KSms 1.0.1

**Comment by Uafinder** [comment]
Ok looks good
