### ISSUE TITLE
Gift vouchers - CSV import

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#79]
Should be able to upload a spreadsheet of vouchers to the voucher type admin page

See https://github.com/Kademi/kademi-dev/issues/32

**Comment by bradmac** [comment]
Please add an ID column and allowing updates. If no ID is present do an insert, if an ID is present attempt to update, but add the line to unmatched if its not found.

Make sure that change records are created when updating via CSV (use the Voucher.changeStatus method)

We need to validate that 
 - the voucher code is unique within the voucher type
 - the redeeming org is valid (if not blank), and link it to an organisation by the OrgID field
 - the redeemed field is valid if not blank, and link it to a Profile by name or email address

**Comment by YOULee** [comment]
#79,  coding is done.
Changed class/html as below:
1)	manageVoucherType.html
2)	ManageVoucherTypeFolder.java

And the added one is:
VouchersCsvPage.java

**Comment by YOULee** [comment]
it was done.

And the CSV file columns(fields) as below: 
1)	Voucher ID
2)	Status
3)	Status Date  (dd/MM/yyyy HH:mm)
4)	Allocated to
5)	Redeeming organization ID
6)	Redeemed by	 (email address)

**Comment by bradmac** [comment]
Could you please move this out of Website and into its own persistent class (ie WebsiteCertificate) in the fuse-server project? As discussed on skype:
[9:42:09 AM] Brad McEvoy: I think we will probably add a table related to website
[9:42:32 AM] Brad McEvoy: Which you could put into the kademi project, so you might not need to change Website.java at all
[9:44:02 AM] Brad McEvoy: it would be good to allow multiple certificates with expiry dates

This should have an expiry date and will allow multiple certificates to be configured for continuity.

Each WebsiteCertificate record should contain:
 - the contents of the certificate
 - the expiry date
 - a reference to the Website
 - information about the signing authority, etc

**Comment by bradmac** [comment]
Thanks!

**Comment by YOULee** [comment]
it is done!

**Comment by Uafinder** [comment]
1. About Export:
It exports all vouchers from all voucher types of org. Is this correct? There is no Voucher Type column in the table to define what Voucher Type this voucher demands.
2. About Export:
Redeeming Org column is empty. Is this correct?
3. 
![image](https://cloud.githubusercontent.com/assets/1945230/5965250/717808a4-a803-11e4-92e1-95874cfdcd21.png)
- What does it means - invalid status date? I've just export this rows a minute ago?
- Looks like there is no possibility to add vouchers in idle state. Is this correct?

**Comment by bradmac** [comment]
"About Export: It exports all vouchers from all voucher types of org. Is this correct? " - No, that was not correct. It should only export vouchers for the current voucher type. Fixed

**Comment by bradmac** [comment]
"About Export: Redeeming Org column is empty. Is this correct?" -- The redeeming organisation was not being set. It is being set now and is displayed. Fixed.

**Comment by bradmac** [comment]
"What does it means - invalid status date? I've just export this rows a minute ago?" - Fixed. But note you will probably need to specify a date format in the column header, for example:

Voucher,Status,Date dd/MM/yyyy,Allocated to,Redeeming org,Redeemed by

This is now added to the export CSV.

**Comment by bradmac** [comment]
"Looks like there is no possibility to add vouchers in idle state. Is this correct?" - That is not correct, but has been Fixed.

**Comment by Uafinder** [comment]
about export bugs - both fixed.
1. Looks like still no possibility to import idle vouchers. I've tried this in line 7 (csv file screenshot) - have a blank status field error.
2. Looks like still existing a problem with date format. I've not been able to import those which i've just export.
![image](https://cloud.githubusercontent.com/assets/1945230/6027618/09de7768-abec-11e4-8724-1d8049bd75c0.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6027623/122814d8-abec-11e4-98db-b430e474fb01.png)

**Comment by tuzzmaniandevil** [comment]
"2. Looks like still existing a problem with date format. I've not been able to import those which i've just export." - Should be fixed Now

**Comment by tuzzmaniandevil** [comment]
"1. Looks like still no possibility to import idle vouchers. I've tried this in line 7 (csv file screenshot) - have a blank status field error."  - @bradmac is this correct?

**Comment by Uafinder** [comment]
Looks like both upper bugs are fixed. Tried to upload CSV and faced some problems again:
1. Export: when we are exporting vouchers to CSV it put's a Name and Surname to a column named "Redeemed by". But when you will try to upload CSV file back, it will tells you that no email is detected. Which means that comparison is going  by emails. So, we should change export for exporting a right info.
![image](https://cloud.githubusercontent.com/assets/1945230/6047826/c03d9e58-acb4-11e4-8462-07227385e3cc.png)
2. There is no possibility to upload a voucher in status which are different from Idle. When uploading status, date and other columns are ignored and voucher are uploaded as Idle.

**Comment by bradmac** [comment]
"1. Export: when we are exporting vouchers to CSV it put's a Name and Surname to a column named "Redeemed by". But when you will try to upload CSV file back, it will tells you that no email is detected. Which means that comparison is going by emails. So, we should change export for exporting a right info."

<-- Fixed. Now exports email and name. Only email is used on upload to identify users

**Comment by bradmac** [comment]
"2. There is no possibility to upload a voucher in status which are different from Idle. When uploading CSV file status, date and other columns are ignoring and voucher are uploaded as Idle." <-- Fixed

**Comment by Uafinder** [comment]
1. Fixed - Ok
2. Couldn't check, because of next bug:

![image](https://cloud.githubusercontent.com/assets/1945230/6235282/ff5cbabc-b6e9-11e4-8288-929e7738e4d7.png)
It can't match redeemer org by name.

**Comment by bradmac** [comment]
now exports the OrgID instead of org name, so should match on import

**Comment by Uafinder** [comment]
Yeap, looks fixed both.
But it's still ignoring date column. i've uploaded vouchers with different dates but gain "less then a minute ago" created date.
![image](https://cloud.githubusercontent.com/assets/1945230/6335815/d8bec078-bba6-11e4-898f-9d79e57fba0b.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6335807/cc438658-bba6-11e4-8184-e796a9be611c.png)

**Comment by Uafinder** [comment]
Nope, still active!
